### PR TITLE
fixing rails4 compatibility

### PR DESCRIPTION
**Pull request by mp-jgoetzinger**
hey, as i needed to extend the client a bit and we're working on rails4 i first had to get the specs passing. these are the changes i made. i also had to bump the database_cleaner version to 1.0.1 (which is working with rails4 but all versions > 1.1 currently don't work with sqlite).

i'm going to open another PR for the extension i made to the client. then you can decide if this would be useful for other people as well.

cheers,
johannes.

### CODE REVIEW

**Comment by jrochkind** [comment]
Are there any plans to release a version of this gem that works under Rails 4? Is this gem still actively maintained/supported?

**Comment by zuk** [comment]
I'm not actively involved in the gem anymore, but from what I occasionally
 see on GitHub and on this mailing list, a number of people are keeping it
going. Not sure what the plans are for Rails 4, but hopefully someone else
will chime in.

On Sat, Feb 21, 2015 at 1:02 PM, Jonathan Rochkind <notifications@github.com

**Comment by akshaysn1991** [comment]
environment.rb
---------------------
CASClient::Frameworks::Rails::Filter.configure(
  :cas_base_url => "http://localhost:8888/",
  :enable_single_sign_out => true,
  :ticket_store => :active_record_ticket_store
)
these are my settings. registrations, login are working fine. 
But I am getting below error when i am signing out. any help would be appreciated
NoMethodError (undefined method `ticket_store' for #<CASClient::Client:0x00000004e61578>):
